trigger: none
pool: MYAGENTDEV
stages:
  - stage: terraforminit
    displayName: INIT
    jobs:
      - job: terraformInit
        displayName: TINIT
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
            backendServiceArm: 'DEVSERV'
            backendAzureRmResourceGroupName: 'IMRG1'
            backendAzureRmStorageAccountName: 'imstg'
            backendAzureRmContainerName: 'imctr'
            backendAzureRmKey: 'terraform.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
            environmentServiceNameAzureRM: 'DEVSERV'
